Workiva/scip-dart

.github/workflows/checks.yaml
.github/workflows/tests.yaml
CHANGELOG.md
Dockerfile
README.md
dart_dependency_validator.yaml
pubspec.yaml

In order for `dart pub publish` to work, we need a changelog, and dep validator cannot showup within the pubspec.yaml
Made these changes, and also updated the readme with the new method for installing pub (once that is available)

FEA-1767: Updates for pub publish

---

CHANGELOG.md

OSS dart repos like to have an up to date changelog. Updated this for the 1.1.0 release

Preped CHANGELOG for 1.1.0 release

---

.github/workflows/checks.yaml
.github/workflows/tests.yaml
analysis_options.yaml
bin/scip_dart.dart
lib/src/flags.dart
lib/src/indexer.dart
lib/src/scip_visitor.dart
lib/src/symbol.dart
lib/src/utils.dart
pubspec.lock
pubspec.yaml
tool/dart_dev/config.dart

Closes #59 
Running `scip-dart` on a dart package with a nested pubspec.yaml file would result in an error (see #59), this pr ignores any subdirectories that declare their own pubspec.yaml file
If nested directories want to be indexed as well, scip-dart can just be re-run on that path
Also, as a QoL update, if the root path provided to `scip_dart ./path` did not contain a pubspec.yaml file, the cli logs an error and fails with a non-zero exit code.
some CI changes are in this pr as well:
- fixed a bug where formatting was not failing when it detected changes
- added an analysis step to ensure analysis passes, implemented default analysis rules, and disabled implicit casts

FEA-2048: Ignore nested subpackages

---

pubspec.yaml

* [Preped CHANGELOG for 1.1.0 release](https://github.com/Workiva/scip-dart/pull/58)
* [FEA-2048: Ignore nested subpackages](https://github.com/Workiva/scip-dart/pull/60)
* [Updated changelog for 1.1.1 release](https://github.com/Workiva/scip-dart/pull/61)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.1.0...Workiva:release_scip-dart_1.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.1.0...1.1.1
This pull request can be recreated by clicking …

RM-199397 Release scip-dart 1.1.1

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [FEA-2108: Populate ToolInfo Version](https://github.com/Workiva/scip-dart/pull/65)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.1.1...Workiva:release_scip-dart_1.1.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.1.1...1.1.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5246720260440064/?repo_name=Workiva%2Fscip-dart&pull_number=66)

RM-199946 Release scip-dart 1.1.2

---

Makefile
lib/src/indexer.dart
pubspec.lock

`ProjectRoot` declared within the generated scip bindings was in the format of `file://path/to/root`, `file://` is an invalid uri, and needs to be in the format of `file:///`
This pr utilizes `Uri.file().toString` to correctly generate the necessary uri
Fixes the issue with running `scip stats` as reported here: https://github.com/sourcegraph/scip/issues/98

Fixed projectRoot URI calculation

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [Fixed projectRoot URI calculation](https://github.com/Workiva/scip-dart/pull/70)
* [Bump args from 2.4.1 to 2.4.2](https://github.com/Workiva/scip-dart/pull/71)
* [Bump glob from 2.1.1 to 2.1.2](https://github.com/Workiva/scip-dart/pull/72)
* [FEA-2357: Put relationship indexing behind a flag](https://github.com/Workiva/scip-dart/pull/77)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.1.3...Workiva:release_scip-dart_1.1.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.1.3...1.1.4 …

RM-203432 Release scip-dart 1.1.4

---

.github/dependabot.yml
.vscode/launch.json
lib/src/scip_visitor.dart
pubspec.lock
snapshots/input/basic-project/lib/more.dart
snapshots/output/basic-project/lib/more.dart

FEA-2421: Fixed Functions as Parameters

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [Bump analyzer from 5.6.0 to 5.13.0](https://github.com/Workiva/scip-dart/pull/75)
* [Bump args from 2.4.1 to 2.4.2](https://github.com/Workiva/scip-dart/pull/81)
* [Bump glob from 2.1.1 to 2.1.2](https://github.com/Workiva/scip-dart/pull/83)
* [FEA-2496: Fixed Cascade Indexing](https://github.com/Workiva/scip-dart/pull/84)
* [FEA-2421: Fixed Functions as Parameters](https://github.com/Workiva/scip-dart/pull/88)
* [Update dev dependencies for analyzer 2](https://github.com/Workiva/scip-dart/pull/90)
* [Bump dart_dev from 4.0.1 to 4.0.2](https://github.com/Workiva/scip-dart/pull/95)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.1.4...Workiva:release_scip-dart_ …

FEA-2358 Release scip-dart 1.1.5

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [FEA-2796: Occurrence Diagnostics](https://github.com/Workiva/scip-dart/pull/94)
* [Bump dependency_validator from 3.2.2 to 3.2.3](https://github.com/Workiva/scip-dart/pull/97)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.1.5...Workiva:release_scip-dart_1.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.1.5...1.2.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5246720260440064/?repo_name=Workiva%2Fscip-dar …

FEA-2503 Release scip-dart 1.2.0

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [Diagnostic bug fixes (and snapshot tests)](https://github.com/Workiva/scip-dart/pull/100)
* [Dart 2.19](https://github.com/Workiva/scip-dart/pull/102)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.2.0...Workiva:release_scip-dart_1.2.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.2.0...1.2.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5246720260440064/?repo_name=Workiva%2Fscip-dart&pull_number=103)

FEA-2798 Release scip-dart 1.2.1

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [Default index-relationships to true](https://github.com/Workiva/scip-dart/pull/104)
* [Bump dart_dev from 4.0.2 to 4.1.0](https://github.com/Workiva/scip-dart/pull/105)
* [Bump workiva_analysis_options from 1.3.0 to 1.4.1](https://github.com/Workiva/scip-dart/pull/107)
* [added codeowners](https://github.com/Workiva/scip-dart/pull/108)
* [FEA-3101: Added ast-printer dev tool](https://github.com/Workiva/scip-dart/pull/109)
* [FEA-3206: Fix NormalFormalParameters](https://github.com/Workiva/scip-dart/pull/111)
* [FEA-3236: Latest scip cli and diagnostic snapshot generation](https://github.com/Workiva/scip-dart/pull/112)
* [FEA-3239: Updated scip Protobuf](https://github.com/Workiva/scip-dart/pull/114) …

FEA-2871 Release scip-dart 1.3.0

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [FEA-3404: export SymbolGenerator](https://github.com/Workiva/scip-dart/pull/122)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.3.0...Workiva:release_scip-dart_1.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.3.0...1.4.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5246720260440064/?repo_name=Workiva%2Fscip-dart&pull_number=123)

FEA-3266 Release scip-dart 1.4.0

---

lib/src/scip_visitor.dart
lib/src/symbol_generator.dart
snapshots/input/basic-project/lib/more.dart
snapshots/output/basic-project/lib/more.dart
snapshots/output/basic-project/lib/other.dart

There are 2 parts to getting a symbol representation of a dart reference/definition: selecting the correct `Element` based on a provided `AstNode`, and building the string using that selected element
Before this PR, the element selection part was done directly within the scip_visitor, which is not exported from scip-dart. This PR moves all of this logic to the symbol_generator, which _is_ exported and available
The SymbolGenerator was selected as the `elementFor` method is a necessary step in symbol generation. It seemed like a fitting, and convenient place (due to the pre-existing exporting of the class)
Also, unrelated, but closes #37 and closes #120

FEDX-1213: Localized element selection logic to the SymbolGenerator

---

lib/src/version.dart
pubspec.yaml

* [SBOM from GHA - again](https://github.com/Workiva/scip-dart/pull/125)
* [Bump dependency_validator from 3.2.3 to 4.0.0](https://github.com/Workiva/scip-dart/pull/126)
* [Bump dependency_validator from 4.0.0 to 4.1.0](https://github.com/Workiva/scip-dart/pull/127)
* [FEDX-1213: Localized element selection logic to the SymbolGenerator](https://github.com/Workiva/scip-dart/pull/128)
* [Updated Changelog for 1.4.1](https://github.com/Workiva/scip-dart/pull/130)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.4.0...Workiva:release_scip-dart_1.4.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.4.0...1.4.1
The logs for the request …

FEA-3407 Release scip-dart 1.4.1

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml

We now have [Workiva/gha-dart-oss](https://github.com/Workiva/gha-dart-oss) to establish the boilerplate of some of the github actions in oss repos
Updated this repo to rely on this, which includes auto-publishing to pub.dev

FEDX-1388: Implement gha-dart-oss

---

.github/dependabot.yml
.github/workflows/ci.yaml
.github/workflows/publish.yaml

We want to monitor gha dependencies and keep them up to date
This change will also test: https://github.com/Workiva/gha-dart-oss/pull/13

FEDX-1401: Added dependentabot for gha

---

pubspec.yaml

There's not really a good reason that we're supporting a lower bound of dart `2.18`, bumping the project to a lower bound of `2.19`, so we can implement the most up to date [analyzer](https://pub.dev/packages/analyzer/versions) version that still supports dart 2
There's active work to figure out the best way of supporting both dart 2 and 3, this is somewhat of a precursor to that work

FEDX-1453: dart 2.19 min

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [FEDX-1401: Added dependentabot for gha](https://github.com/Workiva/scip-dart/pull/134)
* [Bump actions/checkout from 3 to 4](https://github.com/Workiva/scip-dart/pull/135)
* [FEDX-1453: dart 2.19 min](https://github.com/Workiva/scip-dart/pull/138)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.4.2...Workiva:release_scip-dart_1.4.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.4.2...1.4.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerRelea …

FEDX-1391 Release scip-dart 1.4.3

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [Bump Workiva/gha-dart-oss from 0.1.1 to 0.1.2](https://github.com/Workiva/scip-dart/pull/139)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.4.3...Workiva:release_scip-dart_1.4.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.4.3...1.4.4
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5246720260440064/?repo_name=Workiva%2Fscip-dart&pull_number=140)

FEDX-1455 Release scip-dart 1.4.4

---

lib/src/kind_generator.dart
lib/src/scip_visitor.dart

Currently, indexed symbols are just the symbol as declared by the [scip spec](https://github.com/sourcegraph/scip/blob/main/scip.proto#L154)
This implies there's no way to tell the difference between a `class Foo` symbol, a `mixin Foo` symbol, and a `extension Foo` symbol
This PR populates the `kind` field on the scip symbol to resolve this, and enable deeper information about each indexed symbol provided by scip-dart
- Kind is not currently included within snapshot results, lets index the snapshot directory and manually verify `kind` using `scip print`
- Once https://github.com/sourcegraph/scip/pull/236 is merged, I'll consider adding `kind` annotation selections so we can write targeted unit tests for this concept

FEDX-1648: Added symbol kind support

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [Bump Workiva/gha-dart-oss from 0.1.2 to 0.1.3](https://github.com/Workiva/scip-dart/pull/141)
* [Bump dart_dev from 4.1.1 to 4.2.0](https://github.com/Workiva/scip-dart/pull/142)
* [Bump Workiva/gha-dart-oss from 0.1.3 to 0.1.5](https://github.com/Workiva/scip-dart/pull/143)
* [Bump Workiva/gha-dart-oss from 0.1.5 to 0.1.6](https://github.com/Workiva/scip-dart/pull/145)
* [FEDX-1648: Added symbol kind support](https://github.com/Workiva/scip-dart/pull/146)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.4.4...Workiva:release_scip-dart_1.5.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.4.4...1.5.0
The logs for the request …

FEDX-1471 Release scip-dart 1.5.0

---

.github/workflows/ci.yaml
CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [FEDX-1655: Added missing kinds](https://github.com/Workiva/scip-dart/pull/149)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.5.0...Workiva:release_scip-dart_1.5.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.5.0...1.5.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5246720260440064/?repo_name=Workiva%2Fscip-dart&pull_number=150)

FEDX-1649 Release scip-dart 1.5.1

---

.github/workflows/ci.yaml
lib/src/relationship_generator.dart
lib/src/symbol_generator.dart
snapshots/input/basic-project/lib/relationships.dart
snapshots/output/basic-project/lib/relationships.dart

getters, setters, and fields were not correctly indexing their relationships. This PR fixes that (Closes #151)
Also closes #119, because that was necessary in order to get the relationships fixed

FEDX-1670: Fixed getters, setters, and field relationships

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [FEDX-1670: Fixed getters, setters, and field relationships](https://github.com/Workiva/scip-dart/pull/152)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.5.1...Workiva:release_scip-dart_1.5.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.5.1...1.5.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5246720260440064/?repo_name=Workiva%2Fscip-dart&pull_number=154)

FEDX-1660 Release scip-dart 1.5.2

---

snapshots/input/basic-project/pubspec.yaml
snapshots/input/diagnostics/pubspec.yaml
snapshots/input/staging-project/pubspec.yaml

For Dart packages that have migrated to null safety (full or partial)
we can raise the minimum Dart SDK version to 2.19.0 instead of 2.12.0.
This will allow us to take advantage of new language features as soon as
files are migrated to null safety. We've shown that unmigrated consumers
do not have issues consuming packages with a higher minimum Dart SDK version.
- Raise minimum Dart SDK version to 2.19.0
[_Created by Sourcegraph batch change `Workiva/raise_min_dart_sdk_2_19`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/raise_min_dart_sdk_2_19)

raise_min_dart_sdk_2_19

---

lib/src/version.dart
pubspec.yaml

* [Bump workiva_analysis_options from 1.4.1 to 1.4.2](https://github.com/Workiva/scip-dart/pull/156)
* [Bump Workiva/gha-dart-oss from 0.1.6 to 0.1.7](https://github.com/Workiva/scip-dart/pull/157)
* [Bump dart_dev from 4.2.0 to 4.2.2](https://github.com/Workiva/scip-dart/pull/158)
* [raise_min_dart_sdk_2_19](https://github.com/Workiva/scip-dart/pull/159)
Requested by: @robbecker-wf
@Workiva/release-management-p
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.5.2...Workiva:release_scip-dart_1.5.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.5.2...1.5.3
The logs for the request that created this PR can be found …

FEDX-1674 Release scip-dart 1.5.3

---

Makefile
lib/src/scip_visitor.dart
lib/src/symbol_generator.dart
snapshots/input/basic-project/lib/more.dart
snapshots/input/basic-project/lib/relationships.dart
snapshots/output/basic-project/lib/main.dart
snapshots/output/basic-project/lib/more.dart
snapshots/output/basic-project/lib/other.dart
snapshots/output/basic-project/lib/relationships.dart

FEDX-2227: Fixed logic for constructor references

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [Bump workiva_analysis_options from 1.4.2 to 1.4.3](https://github.com/Workiva/scip-dart/pull/161)
* [Bump dependency_validator from 4.1.0 to 4.1.2](https://github.com/Workiva/scip-dart/pull/162)
* [FEDX-2227: Fixed logic for constructor references](https://github.com/Workiva/scip-dart/pull/165)
@Workiva/release-management-p
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.5.3...Workiva:release_scip-dart_1.5.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.5.3...1.5.4
This pull request …

FEDX-2113 Release scip-dart 1.5.4

---

bin/scip_dart.dart

feat: --output flag

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [feat: --output flag](https://github.com/Workiva/scip-dart/pull/169)
@Workiva/release-management-p
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.5.4...Workiva:release_scip-dart_1.6.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.5.4...1.6.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5246720260440064/?repo_name=Workiva%2Fscip-dart&pull_number=170)

FEDX-2340 Release scip-dart 1.6.0

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

* [Bump dependency_validator from 4.1.2 to 4.1.3](https://github.com/Workiva/scip-dart/pull/171)
* [Bump dart_dev from 4.2.2 to 4.2.3](https://github.com/Workiva/scip-dart/pull/172)
@Workiva/release-management-p
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/scip-dart/compare/1.6.0...Workiva:release_scip-dart_1.6.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/scip-dart/compare/1.6.0...1.6.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5246720260440 …

FEDX-2495 Release scip-dart 1.6.1

---

lib/src/pubspec_indexer.dart
snapshots/output/basic-project/pubspec.yaml
snapshots/output/diagnostics/pubspec.yaml

- `version` is optional within a pubspec file, when its missing scip-dart will hard-fail on a NPE. We should cover this edge case since it is indeed optional. For the cases where the version is missing, use the scip wildcard field
- `publish_to: none` in a pubspec.yaml file implies that the pubspec should not be published. In an effort to not encounter many duplicates caused from this, we should consider `publish_to: none` an indication that no other pubspecs will be referencing this one, so we can omit the file symbol

FEDX-2979: Pubspec Indexing followups
